/*
 * This file is generated by jOOQ.
 */
package serol.jooqtry.database.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;
import serol.jooqtry.database.jooq.tables.Blogs;

import javax.annotation.processing.Generated;


/**
 * A class modelling indexes of tables of the <code>jooqtry</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BLOGS_PKEY = Indexes0.BLOGS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index BLOGS_PKEY = Internal.createIndex("blogs_pkey", Blogs.BLOGS, new OrderField[] { Blogs.BLOGS.ID }, true);
    }
}
