/*
 * This file is generated by jOOQ.
 */
package serol.jooqtry.database.jooq;


import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import serol.jooqtry.database.jooq.tables.Blogs;

import javax.annotation.processing.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jooqtry extends SchemaImpl {

    private static final long serialVersionUID = 211608585;

    /**
     * The reference instance of <code>jooqtry</code>
     */
    public static final Jooqtry JOOQTRY = new Jooqtry();

    /**
     * The table <code>jooqtry.blogs</code>.
     */
    public final Blogs BLOGS = serol.jooqtry.database.jooq.tables.Blogs.BLOGS;

    /**
     * No further instances allowed
     */
    private Jooqtry() {
        super("jooqtry", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.BLOGS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Blogs.BLOGS);
    }
}
