/*
 * This file is generated by jOOQ.
 */
package serol.jooqtry.database.jooq;


import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import serol.jooqtry.database.jooq.tables.Blogs;
import serol.jooqtry.database.jooq.tables.records.BlogsRecord;

import javax.annotation.processing.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>jooqtry</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<BlogsRecord, Integer> IDENTITY_BLOGS = Identities0.IDENTITY_BLOGS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BlogsRecord> BLOGS_PKEY = UniqueKeys0.BLOGS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<BlogsRecord, Integer> IDENTITY_BLOGS = Internal.createIdentity(Blogs.BLOGS, Blogs.BLOGS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<BlogsRecord> BLOGS_PKEY = Internal.createUniqueKey(Blogs.BLOGS, "blogs_pkey", Blogs.BLOGS.ID);
    }
}
