/*
 * This file is generated by jOOQ.
 */
package serol.jooqtry.database.jooq;


import serol.jooqtry.database.jooq.tables.Blogs;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in jooqtry
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooqtry.blogs</code>.
     */
    public static final Blogs BLOGS = Blogs.BLOGS;
}
