/*
 * This file is generated by jOOQ.
 */
package serol.jooqtry.database.jooq.tables.pojos;


import javax.annotation.processing.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Blogs implements Serializable {

    private static final long serialVersionUID = 228536274;

    private final Integer   id;
    private final String    author;
    private final Timestamp datePublished;
    private final Timestamp dateEdited;
    private final String    text;

    public Blogs(Blogs value) {
        this.id = value.id;
        this.author = value.author;
        this.datePublished = value.datePublished;
        this.dateEdited = value.dateEdited;
        this.text = value.text;
    }

    public Blogs(
        Integer   id,
        String    author,
        Timestamp datePublished,
        Timestamp dateEdited,
        String    text
    ) {
        this.id = id;
        this.author = author;
        this.datePublished = datePublished;
        this.dateEdited = dateEdited;
        this.text = text;
    }

    public Integer getId() {
        return this.id;
    }

    public String getAuthor() {
        return this.author;
    }

    public Timestamp getDatePublished() {
        return this.datePublished;
    }

    public Timestamp getDateEdited() {
        return this.dateEdited;
    }

    public String getText() {
        return this.text;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Blogs other = (Blogs) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (author == null) {
            if (other.author != null)
                return false;
        }
        else if (!author.equals(other.author))
            return false;
        if (datePublished == null) {
            if (other.datePublished != null)
                return false;
        }
        else if (!datePublished.equals(other.datePublished))
            return false;
        if (dateEdited == null) {
            if (other.dateEdited != null)
                return false;
        }
        else if (!dateEdited.equals(other.dateEdited))
            return false;
        if (text == null) {
            if (other.text != null)
                return false;
        }
        else if (!text.equals(other.text))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.author == null) ? 0 : this.author.hashCode());
        result = prime * result + ((this.datePublished == null) ? 0 : this.datePublished.hashCode());
        result = prime * result + ((this.dateEdited == null) ? 0 : this.dateEdited.hashCode());
        result = prime * result + ((this.text == null) ? 0 : this.text.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Blogs (");

        sb.append(id);
        sb.append(", ").append(author);
        sb.append(", ").append(datePublished);
        sb.append(", ").append(dateEdited);
        sb.append(", ").append(text);

        sb.append(")");
        return sb.toString();
    }
}
